### ISSUE TITLE
Preguiça de pegar o celular

### ISSUE THREAD

**Issue by JGMelon22** [Arthur-Juan/golang-first-project#1]
Usa o [GoLand](https://www.jetbrains.com/go/) no lugar do VSCode. Aproveita que a gente tem conta da facul

**Comment by Arthur-Juan** [comment]
![image](https://user-images.githubusercontent.com/65745858/160295751-c9e5250b-7cde-427a-9b55-5a78f0ed6ebd.png)
Eu uso também
Nesse projeto em específico eu não usei por que estava fazendo ele enquanto seguia uma série de outros conceitos, que eu praticava em pastas separas, ai para mim era mais fácil navegar por elas com o vscode por conta de que ele já está no Path

Mas prefiro GoLand mesmo :)
